Copyright = "All rights reserved - 2020"
baseUrl = "https://www.mgasch.com"
canonifyurls = true
paginate = 10
theme = "uBlogger"
title = "mgasch.com"

# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"

enableRobotsTXT = true
# whether to use git commit log
enableGitInfo = false
# whether to use emoji code
enableEmoji = true

[menu]
[[menu.main]]
identifier = "posts"
# you can add extra information before the name (HTML format is supported), such as icons
pre = ""
# you can add extra information after the name (HTML format is supported), such as icons
name = "Posts"
post = ""
url = "/posts/"
# title will be shown when you hover on this menu link.
title = ""
weight = 1
[[menu.main]]
identifier = "tags"
name = "Tags"
post = ""
pre = ""
title = ""
url = "/tags/"
weight = 2
[[menu.main]]
identifier = "about"
name = "About"
post = ""
pre = ""
title = ""
url = "/about/"
weight = 3
[[menu.main]]
identifier = "github"
name = ""
post = ""
pre = "<i class='fab fa-github fa-fw'></i>"
title = "GitHub"
url = "https://github.com/embano1/blog"
weight = 4

[params]
# uBlogger theme version
version = "1.2.X"
# site description
description = "Personal Blog of Michael Gasch"
# site keywords
keywords = ["Blog", "Hugo", "Technology"]
# site default theme ("light", "dark", "auto")
defaultTheme = "auto"
# public git repo url only then enableGitInfo is true
gitRepo = "https://github.com/embano1/blog"
#  which hash function used for SRI, when empty, no SRI is used
# ("sha256", "sha384", "sha512", "md5")
fingerprint = ""
#  date format
dateFormat = "2006-01-02"
# website images for Open Graph and Twitter Cards
images = ["/images/gopher.jpg"]

#  App icon config
[params.app]
# optional site title override for the app when added to an iOS home screen or Android launcher
# title = "uBlogger"
# whether to omit favicon resource links
noFavicon = false
# modern SVG favicon to use in place of older style .png and .ico files
svgFavicon = ""
# Android browser theme color
themeColor = "#ffffff"
# Safari mask icon color
iconColor = "#5bbad5"
# Windows v8-10 tile color
tileColor = "#da532c"

# Search config
[params.search]
enable = true
# type of search engine ("lunr", "algolia")
type = "lunr"
# max index length of the chunked content
contentLength = 4000
# placeholder of the search bar
placeholder = ""
# max number of results length
maxResultLength = 10
# snippet length of the result
snippetLength = 30
#  HTML tag name of the highlight part in results
highlightTag = "em"
#  whether to use the absolute URL based on the baseURL in search index
absoluteURL = false
[params.search.algolia]
appID = ""
index = ""
searchKey = ""

# Header config
[params.header]
# desktop header mode ("fixed", "normal", "auto")
desktopMode = "fixed"
# mobile header mode ("fixed", "normal", "auto")
mobileMode = "auto"
#  Header title config
[params.header.title]
# URL of the LOGO
logo = ""
# title name
name = "Home of a curious mind"
# you can add extra information before the name (HTML format is supported), such as icons
pre = "<i class='fas fa-pencil-alt fa-fw'></i>"
# you can add extra information after the name (HTML format is supported), such as icons
post = ""
#  whether to use typeit animation for title name
typeit = false

# Footer config
[params.footer]
enable = true
#  Custom content (HTML format is supported)
custom = ''
#  whether to show Hugo and theme info
hugo = false
#  whether to show copyright info
copyright = true
#  whether to show the author
author = true
# Site creation time
since = 2017
# ICP info only in China (HTML format is supported)
icp = ""
# license info (HTML format is supported)
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

#  Section (all posts) page config
[params.section]
# special amount of posts in each section page
paginate = 10
# date format (month and day)
dateFormat = "01-02"
# amount of RSS pages
rss = 10

#  List (category or tag) page config
[params.list]
# special amount of posts in each list page
paginate = 10
# date format (month and day)
dateFormat = "01-02"
# amount of RSS pages
rss = 10

# Home page config
[params.home]
#  amount of RSS pages
rss = 10
# Home page profile
[params.home.profile]
enable = true
# Gravatar Email for preferred avatar in home page
gravatarEmail = ""
# URL of avatar shown in home page
avatarURL = "/images/gopher.jpg"
#  title shown in home page (HTML format is supported)
title = ""
# subtitle shown in home page
subtitle = "Do not go gentle into this good night. Rage."
# whether to use typeit animation for subtitle
typeit = true
# whether to show social links
social = true
#  disclaimer (HTML format is supported)
disclaimer = ""
# Home page posts
[params.home.posts]
enable = true
# special amount of posts in each home posts page
paginate = 5
#  replaced with hiddenFromHomePage in params.page
# default behavior when you don't set "hiddenFromHomePage" in front matter
defaultHiddenFromHomePage = false

# Social config about the author
[params.social]
Angellist = ""
Bandcamp = ""
Behance = ""
Bilibili = ""
Bitbucket = ""
Codepen = ""
Deviantart = ""
Devto = ""
Douban = ""
Dribbble = ""
Email = ""
Facebook = ""
Fivehundredpx = ""
Flickr = ""
Foursquare = ""
FreeCodeCamp = ""
GitHub = "embano1"
Gitea = ""
Gitlab = ""
Goodreads = ""
Googlescholar = ""
Hackernews = ""
Instagram = ""
Jsfiddle = ""
Keybase = ""
Kickstarter = ""
Lastfm = ""
Linkedin = ""
Mastodon = ""
Matrix = ""
Medium = ""
Mix = ""
Odnoklassniki = ""
Patreon = ""
Paypal = ""
Pinterest = ""
Quora = ""
RSS = true
Reddit = ""
Researchgate = ""
Skype = ""
Slidershare = ""
Snapchat = ""
Soundcloud = ""
Spotify = ""
Stackoverflow = ""
Steam = ""
Strava = ""
Telegram = ""
Thingiverse = ""
Tumblr = ""
Twitch = ""
Twitter = "embano1"
VK = ""
Vine = ""
Weibo = ""
Whatsapp = ""
Wordpress = ""
XMPP = ""
Xing = ""
Youtubechannel = ""
Youtubecustom = ""
Youtubelegacy = ""
Zhihu = ""

# Page config
[params.page]
#  main subject for articles, by default classic. more on themes}
theme = "classic"
#  whether to hide a page from home page
hiddenFromHomePage = false
#  whether to hide a page from search results
hiddenFromSearch = false
#  Allows you to hide the preview image on the article page
hiddenFeaturedImage = false
#  whether to enable twemoji
twemoji = false
# whether to enable lightgallery
lightgallery = true
#  whether to enable the ruby extended syntax
ruby = true
#  whether to enable the fraction extended syntax
fraction = true
#  whether to enable the fontawesome extended syntax
fontawesome = true
# whether to show link to Raw Markdown content of the content
linkToMarkdown = true
#  whether to show the full text content in RSS
rssFullText = false
#  Post display settings on the page
[params.page.toc]
# whether to enable the table of the contents
enable = true
#  whether to keep the static table of the contents in front of the post
keepStatic = false
# whether to make the table of the contents in the sidebar automatically collapsed
auto = true
#  KaTeX mathematical formulas
[params.page.math]
enable = true
# default block delimiter is $$ ... $$ and \\[ ... \\]
blockLeftDelimiter = ""
blockRightDelimiter = ""
# default inline delimiter is $ ... $ and \\( ... \\)
inlineLeftDelimiter = ""
inlineRightDelimiter = ""
# KaTeX extension copy_tex
copyTex = true
# KaTeX extension mhchem
mhchem = true
[params.page.code]
# whether to show the copy button of the code block
copy = true
# the maximum number of lines of displayed code by default
maxShownLines = 30
#  Mapbox GL JS config
[params.page.mapbox]
# access token of Mapbox GL JS
accessToken = ""
# style for the light theme
lightStyle = "mapbox://styles/mapbox/light-v9"
# style for the dark theme
darkStyle = "mapbox://styles/mapbox/dark-v9"
# whether to add NavigationControl
navigation = true
# whether to add GeolocateControl
geolocate = true
# whether to add ScaleControl
scale = true
# whether to add FullscreenControl
fullscreen = true
#  social share links in post page
[params.page.share]
Baidu = false
Blogger = false
Buffer = false
Digg = false
Evernote = true
Facebook = true
Flipboard = false
HackerNews = true
Instapaper = false
Line = false
Linkedin = true
Mix = false
Myspace = false
Odnoklassniki = false
Pinterest = false
Pocket = true
Reddit = true
Renren = false
Skype = false
Stumbleupon = false
Trello = true
Tumblr = false
Twitter = true
VK = false
Weibo = false
Whatsapp = false
Xing = false
enable = true
#  Third-party library config
[params.page.library]
[params.page.library.css]
# someCSS = "some.css"
# located in "assets/"
# Or
# someCSS = "https://cdn.example.com/some.css"
[params.page.library.js]
# someJavascript = "some.js"
# located in "assets/"
# Or
# someJavascript = "https://cdn.example.com/some.js"
#  Page SEO config
[params.page.seo]
# image URL
images = []
# Publisher info
[params.page.seo.publisher]
logoUrl = ""
name = ""

[params.summary]
#  Display previews on the page of posts
hiddenImage = false
#  Allows you to hide the description
hiddenDescription = false
#  Allows you to hide the title
hiddenTitle = false
#  Tag display settings
[params.summary.tags]
#  One of the options for displaying tags
theme = "image"
#  Text color
color = "white"
#  Backing color
background = "black"
#  Tag transparency
transparency = 0.9

#  Comment config
[params.comment]
enable = false
# 

# Remark42 comment config
[params.comment.remark42]
enable = false
# the location of your server with Remark42
host = "https://remark.example.com"
# remark42 supports comments for several sites at once, this identifier indicates which site to display comments for.
site = "you_site_key"
# design theme
theme = "light"
# language
locale = "en"
# enable or disable smiley support
emailSubscribe = "true"
# Disqus comment config
[params.comment.disqus]
# 

enable = false
# Disqus shortname to use Disqus in posts
shortname = ""
# Gitalk comment config
[params.comment.gitalk]
# 

clientId = ""
clientSecret = ""
enable = false
owner = ""
repo = ""
# Valine comment config
[params.comment.valine]
appId = ""
appKey = ""
avatar = "mp"
enable = false
enableQQ = false
highlight = true
lang = ""
meta = ""
pageSize = 10
placeholder = ""
recordIP = true
serverURLs = ""
visitor = true
#  emoji data file name, default is "google.yml"
# ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
# located in "themes/uBlogger/assets/data/emoji/" directory
# you can store your own data files in the same path under your project:
# "assets/data/emoji/"
emoji = ""
# Facebook comment config
[params.comment.facebook]
appId = ""
enable = false
languageCode = ""
numPosts = 10
width = "100%"
#  Telegram comments config
[params.comment.telegram]
color = ""
colorful = true
dislikes = false
enable = false
height = ""
limit = 5
outlined = false
siteID = ""
#  Commento comment config
[params.comment.commento]
enable = false
#  Utterances comment config
[params.comment.utterances]
enable = false
# owner/repo
darkTheme = "github-dark"
issueTerm = "pathname"
label = ""
lightTheme = "github-light"
repo = ""

#  TypeIt config
[params.typeit]
# typing speed between each step (measured in milliseconds)
speed = 100
# blinking speed of the cursor (measured in milliseconds)
cursorSpeed = 1000
# character used for the cursor (HTML format is supported)
cursorChar = "|"
# cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
duration = -1

# Site verification code config for Google/Bing/Yandex/Pinterest/Baidu
[params.verification]
baidu = ""
bing = ""
google = ""
pinterest = ""
yandex = ""

#  Site SEO config
[params.seo]
# image URL
image = ""
# thumbnail URL
thumbnailUrl = ""

#  Analytics config
[params.analytics]
enable = true
# Google Analytics
[params.analytics.google]
id = "UA-108156810-1"
# whether to anonymize IP
anonymizeIP = true
# Fathom Analytics
[params.analytics.fathom]
id = ""
# server url for your tracker if you're self hosting
server = ""
# 

# Yandex.Metrika
[params.analytics.yandex]
# your meter number
id = ""

#  Cookie consent config
[params.cookieconsent]
enable = true
# text strings used for Cookie consent banner
[params.cookieconsent.content]
dismiss = ""
link = ""
message = ""

#  CDN config for third-party library files
[params.cdn]
# CDN data file name, disabled by default
# ("jsdelivr.yml")
# located in "themes/uBlogger/assets/data/cdn/" directory
# you can store your own data files in the same path under your project:
# "assets/data/cdn/"
data = ""

#  Compatibility config
[params.compatibility]
# whether to use Polyfill.io to be compatible with older browsers
polyfill = false
# whether to use object-fit-images to be compatible with older browsers
objectFit = false

# Markup related config in Hugo
[markup]
# Syntax Highlighting
[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = true
# false is a necessary configuration
noClasses = false
# Goldmark is from Hugo 0.60 the default library used for Markdown
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.renderer]
# whether to use HTML tags directly in the document
unsafe = true
# Table Of Contents settings
[markup.tableOfContents]
endLevel = 6
startLevel = 2

# Author config
# 

[author]
name = "Michael Gasch"

# Sitemap config
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

# Permalinks config
[Permalinks]
posts = ":year/:month/:filename"
# posts = ":filename"

# Privacy config
[privacy]
#  privacy of the Google Analytics (replaced by params.analytics.google)
[privacy.googleAnalytics]
# ...
[privacy.twitter]
enableDNT = true
[privacy.youtube]
privacyEnhanced = true

# Options to make output .md files
[mediaTypes]
[mediaTypes."text/plain"]
suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
isHTML = false
isPlainText = true
mediaType = "text/plain"

# Options to make hugo output files
[outputs]
# 

home = ["HTML", "RSS", "JSON"]
page = ["HTML", "MarkDown"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
taxonomyTerm = ["HTML"]
